model_list:
  - model_name: qwen3-embedding-4b
    litellm_params:
      model: openai/qwen3-embedding-4b
      api_base: https://chat-ai.academiccloud.de/v1
      api_key: os.environ/ACADEMIC_CLOUD_API_KEY
  - model_name: text-embedding-ada-002
    litellm_params:
      model: openai/text-embedding-ada-002
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY